apiVersion: v1
kind: Pod
metadata:
  labels:
    run: httpd-me
  name: httpd-me
spec:
  containers:
  - image: httpd
    name: httpd-me
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
